echo '/////////////////////////////////////////////' >> server.cfg
echo '// OSP Server Configuration File //' >> server.cfg
echo '// //' >> server.cfg
echo '// Generated by OSP Config File Generator //' >> server.cfg
echo '// on 12/14/2006 11:07:17 //' >> server.cfg
echo '// //' >> server.cfg
echo '// Written by v1l3 //' >> server.cfg
echo '/////////////////////////////////////////////' >> server.cfg
echo '' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Gameplay Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set capturelimit "'$QJS_CAPTURELIMIT'"' >> server.cfg
echo 'set dmflags "0"' >> server.cfg
echo 'set fraglimit "'$QJS_FRAGLIMIT'"' >> server.cfg
echo 'set g_dowarmup "1"' >> server.cfg
echo 'set g_forceRespawn "20"' >> server.cfg
echo 'set g_gametype "0"' >> server.cfg
echo 'set g_teamautojoin "0"' >> server.cfg
echo 'set g_teamforcebalance "0"' >> server.cfg
echo 'set g_warmup "20"' >> server.cfg
echo 'set match_carespawn "0"' >> server.cfg
echo 'set match_instagib "0"' >> server.cfg
echo 'set match_latejoin "1"' >> server.cfg
echo 'set match_minplayers "1"' >> server.cfg
echo 'set match_overtime "0"' >> server.cfg
echo 'set match_overtimecount "0"' >> server.cfg
echo 'set match_overtimelength "5"' >> server.cfg
echo 'set match_readypercent "51"' >> server.cfg
echo 'set match_roundtimer "10"' >> server.cfg
echo 'set match_timeoutcount "3"' >> server.cfg
echo 'set match_timeoutlength "60"' >> server.cfg
echo 'set match_winbyscore "0"' >> server.cfg
echo 'set roundlimit "5"' >> server.cfg
echo 'set server_promode "0"' >> server.cfg
echo 'set team_allcaptain "1"' >> server.cfg
echo 'set team_maxplayers "0"' >> server.cfg
echo 'set team_nocontrols "0"' >> server.cfg
echo 'set team_noteamready "0"' >> server.cfg
echo 'set timelimit "'$QJS_TIMELIMIT'"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Server Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set g_gravity "800"' >> server.cfg
echo 'set g_inactivity "0"' >> server.cfg
echo 'set g_knockback "1000"' >> server.cfg
echo 'set g_maxGameClients "0"' >> server.cfg
echo 'set g_motd ""' >> server.cfg
echo 'set g_needpass "0"' >> server.cfg
echo 'set g_smoothclients "0"' >> server.cfg
echo 'set g_speed "320"' >> server.cfg
echo 'set match_maxsuicides "0"' >> server.cfg
echo 'set osp_gamename "1"' >> server.cfg
echo 'set player_always ""' >> server.cfg
echo 'set rconPassword "'$QJS_RCONPASSWORD'"' >> server.cfg
echo 'set ref_password "paws"' >> server.cfg
echo 'set server_customclient "15"' >> server.cfg
echo 'set server_ospauth "0"' >> server.cfg
echo 'set server_record "0"' >> server.cfg
echo 'set server_motd "Quake on AWS"' >> server.cfg
echo 'set sv_allowDownload "1"' >> server.cfg
echo 'set sv_cheats "0"' >> server.cfg
echo 'set sv_floodprotect "0"' >> server.cfg
echo 'set sv_hostname "'$QJS_SV_HOSTNAME'"' >> server.cfg
echo 'set sv_maxclients "'$QJS_SV_MAXCLIENTS'"' >> server.cfg
echo 'set sv_privateClients "0"' >> server.cfg
echo 'set sv_pure "0"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// File Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// set g_log ""' >> server.cfg
echo '// set g_logSync "0"' >> server.cfg
echo '// set log_default "0"' >> server.cfg
echo '// set log_stat "0"' >> server.cfg
echo '// set filter_file "filters.txt"' >> server.cfg
echo '// set map_file "C:\Program Files\Quake III Arena\osp\cfg-maps\ffamaps.txt"' >> server.cfg
echo '// set server_gfxspecific "none"' >> server.cfg
echo '// set player_file "none"' >> server.cfg
echo '// seta server_motdfile ""' >> server.cfg
echo '// set mode_customfilename "none"' >> server.cfg
echo '// set decal_directory "decals"' >> server.cfg
echo '// set viewcam_directory "cfg-viewcam"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Weapon Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set armor_q2style "0"' >> server.cfg
echo 'set gauntlet_damage "50"' >> server.cfg
echo 'set gauntlet_disable "0"' >> server.cfg
echo 'set g_friendlyFire "1"' >> server.cfg
echo 'set g_weaponrespawn "5"' >> server.cfg
echo 'set g_weaponteamrespawn "30"' >> server.cfg
echo 'set instagib_reload "1500"' >> server.cfg
echo 'set item_disable "0"' >> server.cfg
echo 'set match_cawarmupfire "1"' >> server.cfg
echo 'set match_dropitems "0"' >> server.cfg
echo 'set match_hurtself "1"' >> server.cfg
echo 'set mg_damage "7"' >> server.cfg
echo 'set mg_damageTeamplay "5"' >> server.cfg
echo 'set railgun_damage "100"' >> server.cfg
echo 'set server_fastrail "0"' >> server.cfg
echo 'set server_lgcooldown "0"' >> server.cfg
echo 'set server_thrufloors "0"' >> server.cfg
echo 'set start_armor "0"' >> server.cfg
echo 'set start_bfg "0"' >> server.cfg
echo 'set start_bullets "100"' >> server.cfg
echo 'set start_cells "0"' >> server.cfg
echo 'set start_grenades "0"' >> server.cfg
echo 'set start_health "125"' >> server.cfg
echo 'set start_lightning "0"' >> server.cfg
echo 'set start_rockets "0"' >> server.cfg
echo 'set start_shells "0"' >> server.cfg
echo 'set start_slugs "0"' >> server.cfg
echo 'set team_armordamage "0"' >> server.cfg
echo 'set warmup_armor "100"' >> server.cfg
echo 'set weapon_deaddrop "1"' >> server.cfg
echo 'set weapon_have "1"' >> server.cfg
echo 'set weapon_start "257"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Item Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set g_quadfactor "0"' >> server.cfg
echo 'set hook_enable "1"' >> server.cfg
echo 'set hook_delaytime "0"' >> server.cfg
echo 'set hook_holdtime "20"' >> server.cfg
echo 'set hook_sky "0"' >> server.cfg
echo 'set hook_speed "5000"' >> server.cfg
echo 'set hook_pullspeed "1200"' >> server.cfg
echo 'set match_poweruprespawn "60"' >> server.cfg
echo 'set powerup_disable "0"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Voting Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set g_allowvote "1"' >> server.cfg
echo 'set mode_start "-1"' >> server.cfg
echo 'set server_availmodes "63"' >> server.cfg
echo 'set vote_limit "5"' >> server.cfg
echo 'set vote_percent "51"' >> server.cfg
echo 'set vote_allow_altgraphics "1"' >> server.cfg
echo 'set vote_allow_allcaptain "1"' >> server.cfg
echo 'set vote_allow_armordamage "1"' >> server.cfg
echo 'set vote_allow_capturelimit "1"' >> server.cfg
echo 'set vote_allow_ca_startrespawn "1"' >> server.cfg
echo 'set vote_allow_ca_warmupfire "1"' >> server.cfg
echo 'set vote_allow_dropitems "1"' >> server.cfg
echo 'set vote_allow_falling "1"' >> server.cfg
echo 'set vote_allow_fastrail "1"' >> server.cfg
echo 'set vote_allow_fraglimit "1"' >> server.cfg
echo 'set vote_allow_hook "1"' >> server.cfg
echo 'set vote_allow_instagib "1"' >> server.cfg
echo 'set vote_allow_items "1023"' >> server.cfg
echo 'set vote_allow_kick "1"' >> server.cfg
echo 'set vote_allow_lgcooldown "1"' >> server.cfg
echo 'set vote_allow_map "1"' >> server.cfg
echo 'set vote_allow_machinegun "1"' >> server.cfg
echo 'set vote_allow_maxpackets "1"' >> server.cfg
echo 'set vote_allow_mutespecs "1"' >> server.cfg
echo 'set vote_allow_notimer "1"' >> server.cfg
echo 'set vote_allow_osphud "1"' >> server.cfg
echo 'set vote_allow_overtime "1"' >> server.cfg
echo 'set vote_allow_pmove "1"' >> server.cfg
echo 'set vote_allow_poweruprespawn "1"' >> server.cfg
echo 'set vote_allow_powerups "255"' >> server.cfg
echo 'set vote_allow_promode "1"' >> server.cfg
echo 'set vote_allow_reload "1"' >> server.cfg
echo 'set vote_allow_referee "1"' >> server.cfg
echo 'set vote_allow_respawn "1"' >> server.cfg
echo 'set vote_allow_roundlimit "1"' >> server.cfg
echo 'set vote_allow_teamdamage "1"' >> server.cfg
echo 'set vote_allow_thrufloors "1"' >> server.cfg
echo 'set vote_allow_timelimit "1"' >> server.cfg
echo 'set vote_allow_timenudge "1"' >> server.cfg
echo 'set vote_allow_weaponrespawn "1"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Other Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set g_spectatorInactivity "0"' >> server.cfg
echo 'set match_mutespecs "0"' >> server.cfg
echo 'set pmove_fixed "1"' >> server.cfg
echo 'set pmove_msec "8"' >> server.cfg
echo 'set server_maxpacketsmax "0"' >> server.cfg
echo 'set server_maxpacketsmin "0"' >> server.cfg
echo 'set server_realping "0"' >> server.cfg
echo 'set server_timenudgemax "0"' >> server.cfg
echo 'set server_timenudgemin "0"' >> server.cfg
echo 'set sv_maxRate "25000"' >> server.cfg
echo 'set sv_maxPing "0"' >> server.cfg
echo 'set sv_minPing "0"' >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Map Rotation //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set map_autoload "1"' >> server.cfg
echo 'map '$QJS_MAP >> server.cfg
echo '' >> server.cfg
echo '//////////////////////' >> server.cfg
echo '// Bot Options //' >> server.cfg
echo '//////////////////////' >> server.cfg
echo 'set bot_enable "1"' >> server.cfg
echo 'set bot_autoload ""' >> server.cfg
echo 'set bot_checktime "10"' >> server.cfg
echo 'set bot_minplayers "'$QJS_BOT_MINPLAYERS'"' >> server.cfg
echo 'addbot daemia '$QJS_BOT_SKILL >> server.cfg
echo 'addbot grunt '$QJS_BOT_SKILL >> server.cfg
echo 'addbot major '$QJS_BOT_SKILL >> server.cfg
echo 'addbot stripe '$QJS_BOT_SKILL >> server.cfg
echo 'addbot visor '$QJS_BOT_SKILL >> server.cfg

mv server.cfg base/baseq3/server.cfg

node build/ioq3ded.js +set fs_game $QJS_FS_GAME +set dedicated $QJS_DEDICATED +exec $QJS_SERVER_CONFIG
